### ISSUE TITLE
Warnings on directives in 1.0.16

### ISSUE THREAD

**Issue by philipbelesky** [james2doyle/vue-drag-and-drop#3]
Hey, great plugin, it's been super useful! One thing I've noticed is that as of the version of Vue I'm using (1.0.16, development version) console warnings will show for each element that uses a directive on page load. For example if you swap in Vue ```1.0.16``` into the example file you get:

```
vue.js:990 [Vue warn]: Failed to resolve directive: drop
vue.js:990 [Vue warn]: Failed to resolve directive: drag-end
vue.js:990 [Vue warn]: Failed to resolve directive: drag-leave
vue.js:990 [Vue warn]: Failed to resolve directive: drag-enter
vue.js:990 [Vue warn]: Failed to resolve directive: drag-over
vue.js:990 [Vue warn]: Failed to resolve directive: drag-start
vue.js:990 [Vue warn]: Failed to resolve directive: drop
```

This doesn't affect functionality, but can get annoying with large numbers of objects and directives.

**Comment by hamstu** [comment]
@philipbelesky I modified the source so that the props don't start with `v-`, since as you mentioned Vue sees them as directive markers. I'm guessing this is a fairly recent change.

My modifications look like this;

```javascript
[...]
Vue.directive('drag-and-drop', {
      params: [
      'drag-and-drop',
      'drag-start',
      'drag-over',
      'drag-enter',
      'drag-leave',
      'drag-end',
      'drop'
      ],

```

And then do a case sensitive search and replace for `this.params.vD` replacing it with `this.params.d` to fix the internal references to those props.

Example of HTML: `<li v-drag-and-drop drop="handleDrop" dragEnter="handleDragEnter">...</li>`

I should probably just fork it and submit a PR, but let me know if this helps!

:ok_hand:

**Comment by james2doyle** [comment]
Do it up!
